### ISSUE TITLE
Specification Decision Needed: Model Versioning

### ISSUE THREAD

**Issue by caradoxical** [modzy/edge-ai-standards-mqtt#3]
There are two ways to incorporate model versioning into both the MQTT and Sparkplug topic structure:

**Option 1: Merge model name and version with a ":"**
Example `site/area/line/cell/milling_machine/Machine Failure Prediction:0.0.1`
Pros:
- Keeps the namespace less complex
- Leaves more flexibility in versioning styles
- Doesn't require that models are versioned

**Option 2: Create an additional layer in the namespace for version number**
Example `site/area/line/cell/milling_machine/Machine Failure Prediction/0.0.1`
Pros:
- Ensures that AI/ML applications are enforcing model versioning
- Enables data scientists to monitor all model/version combinations across the entire namespace with wildcards

**Comment by bmunday3** [comment]
I like the idea of creating an additional layer in the namespace for a unique version number (option 2). From my perspective, being able to manage, view, and subscribe to topics with predictions on a model-version basis is consistent with MLOps best practices and brings this capability to MQTT.

**Comment by bmunday3** [comment]
A separate thought related to the model name & version, I know the topic naming convention was up for discussion (human readable model name and/or unique model identifier string (e.g., `aidkwn2kd`) in the event that multiple ML models share a common name but are in fact different. One idea might be to optionally combine a unique model identifier with the model version.
Example: `site/area/line/cell/milling_machine/Machine Failure Prediction/aidkwn2kd-0.0.1`

**Comment by caradoxical** [comment]
12/8/23 discussion:

- Separating model name and version as separate namespace elements is agreed to be a good idea
- Continued discussion may be needed to decide to put the version before or after the model name
